---
title: "Formula 1 Championship"
author: "Vish"
date: "27/08/2021"
output: html_document
---




```{r library, warning=FALSE, include=FALSE}
library(plotly)
library(viridis)
library(tidyverse)
```

## Set directory

```{r}
pwd <- getwd()
myfiles <- "Formula1_Data"
data.folder <- paste0(pwd,"/",myfiles)
```

## Import files

```{r}
circuits <- read.csv(paste0(data.folder,"/circuits.csv"))
constructor_results <- read.csv(paste0(data.folder,"/constructor_results.csv"))
constructor_standings <- read.csv(paste0(data.folder,"/constructor_standings.csv"))
constructors <- read.csv(paste0(data.folder,"/constructors.csv"))
driver_standings <- read.csv(paste0(data.folder,"/driver_standings.csv"))
drivers <- read.csv(paste0(data.folder,"/drivers.csv"))
lap_times <- read.csv(paste0(data.folder,"/lap_times.csv"))
pit_stops <- read.csv(paste0(data.folder,"/pit_stops.csv"))
qualifying <- read.csv(paste0(data.folder,"/qualifying.csv"))
races <- read.csv(paste0(data.folder,"/races.csv"))
results <- read.csv(paste0(data.folder,"/results.csv"))
seasons <- read.csv(paste0(data.folder,"/seasons.csv"))
status <- read.csv(paste0(data.folder,"/status.csv"))
```

```{r}
drivers <- drivers %>% 
  mutate(fullname=(paste(surname,forename, sep = ", ")))

constructor_standings_name <- left_join(constructor_standings,constructors,
                                        by=c("constructorId"))
```


```{r}
str(races)
```

## Circuits

```{r}
races_1 <- races %>% 
  group_by(name, circuitId) %>% 
  count(name) %>% 
  rename(Total_Races= n)
```


```{r}
races_join1 <- left_join(races_1, circuits,
                         by =c("circuitId"))
```


```{r}
world_map <- map_data("world")
races_plot1 <- ggplot() +
  geom_polygon(data = world_map, aes(x=long, y = lat, group = group), fill="darkgreen", alpha=0.3) +
  geom_point(data=races_join1, aes(x=lng, y=lat, colour=Total_Races, 
                      text = paste(" Races:",Total_Races,"\n",name.y," \n",location,", ",country)))+
 scale_color_viridis(option="magma", trans="log",name="Total Races", breaks =c(1,5,10,30,60))
  


fig1 <- ggplotly(races_plot1, tooltip="text")
fig1
```

## Drivers 


```{r}
driverstart_join1 <- left_join(driver_standings, drivers,
                         by =c("driverId"))

driverstart_join1 <- driverstart_join1 %>% 
  group_by(driverId) %>% 
  mutate(race_starts=n()) %>% 
  mutate(fullname=(paste(forename, surname,sep = " ")))
```

```{r}
driverstart_plot <- ggplot() +
  geom_bar(data=driverstart_join1,aes(y=reorder(fullname,race_starts),fill=nationality,stat="count"))

fig2 <- ggplotly(driverstart_plot)
fig2
  
```

```{r}
driver_results_join1 <- left_join(results,drivers,
                                  by=c("driverId"))
driver_results_join2 <- left_join(driver_results_join1,constructors,
                                  by=c("constructorId"))
```

```{r}
driver_results_join2_win <- driver_results_join2 %>% 
  filter(position=="1") %>% 
   group_by(driverId, constructorId) %>% 
   mutate(wins=n())
  
```
```{r}
driverstart_win_plot <- driver_results_join2_win %>% 
  count(fullname, name) %>% 
  ggplot() +
  geom_col(aes(x=reorder(fullname,n,sum),y=n, fill=name))+
  coord_flip()

fig3 <- ggplotly(driverstart_win_plot)
fig3
  
```

